### ISSUE TITLE
'Entity Typing' experiment

### ISSUE THREAD

**Issue by renespeck** [AKSW/gerbil#151] opened 2016-10-20 08:53 UTC
Hey, 

I implemented TypedSpanImpl with the help of gerbil.nif.transfer 1.2.3-SNAPSHOT in a webservice. I try to run the experiment 'Entity Typing' with the GUI but  get a warning when GERBIL tests my service: Warning! There was an error while testing the annotator.
Got an unknown experiment type "ETyping".

I get the same warning for a webservice that implement TypedNamedEntity. (e.g.: http://fox-demo.aksw.org/call/ner/entities) 

For the experiment 'Entity Recognition' the GERBIL test passes for all.

In GERBIL I also have gerbil.nif.transfer 1.2.3-SNAPSHOT.

**Comment by MichaelRoeder** [comment] 2016-10-20 09:42
Thanks for the detailed description. The problem should be solved by the last commit. Please checkout the master, try it again and close this issue if the problem is solved.

**Comment by renespeck** [comment] 2016-10-20 09:57
I tested it with http://fox-demo.aksw.org/call/ner/entities but got the same warning again.

**Closed** 2016-10-20 10:36 UTC
Labels: bug

**Comment by renespeck** [comment] 2016-10-20 10:39
Thanks very much for the fast fix.
