### ISSUE TITLE
OKE Example Dataset missing Annotations

### ISSUE THREAD

**Issue by santifa** [AKSW/gerbil#105] opened 2015-12-15 14:00 UTC
I'm using the OKE Datasets for evaluation within D2KB or A2KB and it seems that the gold standard is partially empty. In example the oke example dataset for task 1 didn't have the annotations for the second sentence. I'm unsure if there are not more such failures.

**Comment by MichaelRoeder** [comment] 2015-12-15 14:11
Hi,

we have a JUnit test that is exactly checking the example dataset of task 1 ( https://github.com/AKSW/gerbil/blob/master/src/test/java/org/aksw/gerbil/dataset/impl/nif/OKEChallengeTask1DatasetTest.java ) and this test is green. Thus, we can be pretty sure that it is not a problem of the code.

Are you using the online instance of GERBIL or does the problem occur in your fork of the project?
Can you make sure that the file `gerbil_data/datasets/oke-challenge/example_data/task1.ttl` exists?

**Comment by santifa** [comment] 2015-12-15 16:54
Hi,

I'm using a heavy modified version of gerbil 1.2.0 or 1. I didn't know exactly, but I never touched the dataset configurations or loading parts.
The test is also green by me, but if I change the test file to `gerbil_data/datasets/oke-challenge/example_data/task1.ttl` (fresh downloaded) the test fails.

**Comment by MichaelRoeder** [comment] 2015-12-16 12:05
Hi,

in my version the test is green even if I use the dataset from the gerbil_data path.

How did you downloaded it? Did you use the `start.sh` script? Please try downloading the `gerbil_data.zip` file from [the last release](https://github.com/AKSW/gerbil/releases/tag/V1.2.1). It should contain the correct file.

What about the other OKE task 1 datasets? Did you experienced problems with them?

**Comment by santifa** [comment] 2015-12-21 15:50
Hi,

sorry for the late response.
First in the OKE datasets the IRI `oke:Sentator_1`  should be `oke:Senator_1` since this what is required in the `OKEChallengeTask1DatasetTest` test.
I expected the failure with the `start.sh`, running a normal annotor and when I'm running the tests provided with Gerbil. 
The initialized RDFModel contains the markings for sentence 2, but the resulting document 
is missing them. 
The other two `TASK 1` datasets `gold standard sample` and `evaluation datasets` are working fine. 

I try to dig through the code, but it may take some time.

**Comment by MichaelRoeder** [comment] 2016-01-04 09:55
Hi,

it seems like I have uploaded an outdated version of the `task1.ttl` file inside the `gerbil_data.zip` file. Locally, I am using a file that does not contain these errors. Thus, I couldn't reproduce them.

Sorry for any inconveniences. I will fix the zip file with the next release.
As a workaround, you can simply copy the file
```
src/test/resources/OKE_Challenge/example_data/task1.ttl
```
to
```
gerbil_data/datasets/oke-challenge/example_data/task1.ttl
```

Cheers,
Michael

**Comment by MichaelRoeder** [comment] 2016-05-11 11:28
Fixed in the data that is offert with version 1.2.2

**Closed by MichaelRoeder** 2016-05-11 11:28 UTC
Labels: bug
