### ISSUE TITLE
[QA] Debug why macro f-measure does not work with Hawk

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#155] opened 2016-10-24 06:08 UTC
Makro F-measure seems to be broken, see experiments

gerbil-qa.aksw.org/gerbil/experiment?id=201610230000
gerbil-qa.aksw.org/gerbil/experiment?id=201610230001

Please investigate

**Comment by TortugaAttack** [comment] 2016-10-28 22:37
Results of yoda (gerbil-qa.aksw.org/gerbil/experiment?id=201610230000) are actually "correct" :D 
The Problem is that the Questions with OUT OF SCOPE will have 0 results. As Yoda was down it has 0 results. makes tp:0 fp:0 fn:0 and therefore (by default of gerbil) is precision 1.0, recall 1.0 and f measure 1.0  
Thus micro is always 0, but macro can be greater than 0

**Comment by RicardoUsbeck** [comment] 2016-10-31 14:32
Actually we need to filter OUT OF SCOPE questions, could you do that and not use them?

**Comment by TortugaAttack** [comment] 2016-10-31 14:54
will fix it

**Comment by TortugaAttack** [comment] 2016-10-31 16:32
OOS will not be tested anymore.

**Comment by RicardoUsbeck** [comment] 2016-11-02 09:49
Cool. So can this issue be closed?

**Comment by TortugaAttack** [comment] 2016-11-02 11:42
Not yet, i tried it without the OOS questions (which worked), but still the (C | P | RE )2KB Experiments have results higher than 0, because the queries of some questions could not be parsed correctly (f.e. a GROUP is missing etc.) thus they have no resource markings etc. and will therefore end into an empty set in these experiments.
Same as the OOS it will have tp=0 , fp=0 , fn=0 and therefore 1. 

Should they be taken out too? 
Further more the ErrorCounter does not work. Will fix that today.

**Comment by MichaelRoeder** [comment] 2016-11-02 13:24
Ok, please add a short summary what the problem of the error count is to make sure whether we have a similar problem in the NER/EL GERBIL

**Comment by TortugaAttack** [comment] 2016-11-02 13:46
the QASystem never throws an Exception, even if the Annotator does, the ASystem of NLIWOD will not. 
It simply returns an IQuestion object with nulls and empty sets.  So it should not be a Problem with NER/EL GERBIL ;) 

Fix will be: if answertype, SparqlQuery and PseudoSparqlQuery will be null and the answer is an empty set, QASystem will throw a GerbilException.

**Comment by RicardoUsbeck** [comment] 2016-11-02 14:47
Ok, so we need to change that in NLIWOD. 
If the SPARQL query cannot be parsed the sub-experiments should not be executed, I think.

**Comment by TortugaAttack** [comment] 2016-11-02 14:58
Ok, will do that. ;)

**Comment by TortugaAttack** [comment] 2016-11-03 18:44
Should all work now with  [ba28621](https://github.com/AKSW/NLIWOD/commit/ba28621cc42998ac1eb410928f81bc776708ee29) and [c24736b](https://github.com/AKSW/NLIWOD/commit/c24736b0da377d77baa6921a99856456f0d3f058) in NLIWOD (dev). Will make a final test and if everything works, i will close the issue

**Comment by RicardoUsbeck** [comment] 2016-11-04 06:15
Please deploy a new higher snapshot version of nliwod to GERBIL right out of the dev branch

**Comment by TortugaAttack** [comment] 2016-11-04 10:06
Deploying it right now ;)

AS NLIWOD is based upon jena 3.1.0 and gerbil-qa uses 2.13.0 i would carefully update the jena dependencies to 3.1.0. So NLIWOD and gerbil-qa will better work together

**Comment by MichaelRoeder** [comment] 2016-11-04 10:12
I have updated GERBIL to jena3.1 in another branch. You might want to reuse it ;)

**Comment by MichaelRoeder** [comment] 2016-11-04 10:13
The name of the other branch is `jena3.1`. https://github.com/AKSW/gerbil/tree/jena3.1

**Closed** 2016-11-04 20:09 UTC
Labels: bug
