### ISSUE TITLE
[QA] Numbers are inprecise

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#183] opened 2017-03-07 09:28 UTC
Why is the precision, recall and F1 not all 1 if I upload the exact answers from the training file. 
Especially the Macro F1 of the first, second and fifth line is 0? 

I just upload the training dataset (qald7-train-multilingual https://github.com/ag-sc/QALD/blob/master/7/data/qald-7-train-multilingual.json ) as the answer file. 

![evaluation-result](https://cloud.githubusercontent.com/assets/4354740/23649993/c6b64b8a-0320-11e7-9160-399402d5f0a1.png)

**Comment by MichaelRoeder** [comment] 2017-03-07 09:43
Please check this using the https://github.com/AKSW/gerbil/blob/QuestionAnswering/src/test/java/org/aksw/gerbil/execute/GoldStdEvalTest.java JUnit test. It should implement exactly this test (a system that provides exactly the responses that are loaded from the gold standard). Than we know whether there is a bug in the evaluation itself or in the processing of uploaded data.

**Comment by TortugaAttack** [comment] 2017-03-08 15:47
The GoldStdEvalTest fails (Macro F1 is 0)
Will fix it.

**Comment by TortugaAttack** [comment] 2017-03-08 15:57
fixed with [1ccdca2](https://github.com/AKSW/gerbil/commit/1ccdca29a6f49f5c8e68a719687d098234142b3d) 
Macro F1 should work now. 
The other part (why P,R,F1 is not always 1 but slightly less) needs to be tested though.

**Comment by TortugaAttack** [comment] 2017-03-08 15:58
@RicardoUsbeck did you use json or xml as upload?

**Comment by MichaelRoeder** [comment] 2017-03-08 15:59
Does the second problem (values < 1) occur in the JUnit test as well?

**Comment by RicardoUsbeck** [comment] 2017-03-08 15:59
It wasn't me directly but I guess it was the json file

**Comment by TortugaAttack** [comment] 2017-03-08 16:00
okay. 
Will test both. 
Nope, the problem did not occur on the JUnit test. 
i even checked the tp, fp etc. they were all perfect. 
I guess it is somehow an error in JSON vs XML

**Comment by MichaelRoeder** [comment] 2017-03-08 16:02
Which makes it a bug of qa.* and not a bug of GERBIL.
I am out :stuck_out_tongue:

**Comment by TortugaAttack** [comment] 2017-03-08 20:41
Nope a bug in Gerbil.. sorry :D
Which is kinda complicated to explain. 
The problem is in the matching. 
If there are two equal elements (f.e. Annotation [a, b,c] is twice in the answer as well as goldenStd) the Matcher will recognize booth elements as one. 
f.e. on Pos 2 and 3 the equal Elements occur. Thus the `EqualBasedMatcherSearcher` returns {1, 2}  and the Matcher will of course only take the first one and adds to the true positives {1} but not {2} 
This is up till now fine, but as soon as the Pos 3 will be checked the `EqualBasedMatcherSearcher`returns again {1,2} instead of only {2} as {1} was already used. 
Thus the Matcher will add again {1} but not {2} leading to not correct false-positives. 

The fix i commited is that the `EqualBasedMatcherSearcher` will remove all already used Positions before returning the matches. 
This leads to: 
Pos 2 will be checked. returns {1,2} adds {1} as match. 
Pos 3 will be chekced. returns {2} as {1} was already added. adds {2} as match. 

If there are three of the same Objects in the answer, but only two in the GoldenStd. The third will be added as false negative. 

Commit is: [857dbce](https://github.com/AKSW/gerbil/commit/857dbce7b7da8f39a84ad0157b68508657e3f5f6)

**Closed** 2017-03-08 20:43 UTC
Labels: bug
